//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect___MVC.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tehnician
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Numele este obligatoriu!")]

        public string Nume { get; set; }
        [Required(ErrorMessage = "Functia este obligatorie!")]
        public string Functie { get; set; }
        public Nullable<int> id_Utilizator { get; set; }
    
        public virtual Utilizator Utilizator { get; set; }
    }
}
